/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe and startup diagnostics
         * @description Always answers 200 while the process is up. `status` is `degraded` when
         *     a check fails (for example the library is not writable), so the UI can
         *     explain the problem instead of the container crash-looping.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a session with the shared password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the session on this device */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consoles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consoles in carousel order */
        get: operations["listConsoles"];
        put?: never;
        /**
         * Add a console for an IGDB platform; it goes last (RF-41)
         * @description Consoles added by the user are detected by extension only.
         */
        post: operations["createConsole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consoles/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the carousel order */
        put: operations["reorderConsoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consoles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a console added by the user that has no games */
        delete: operations["deleteConsole"];
        options?: never;
        head?: never;
        /** Change a console's name, extensions or (without games) its folder */
        patch: operations["updateConsole"];
        trace?: never;
    };
    "/metadata/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search games on IGDB, optionally limited to one platform */
        get: operations["searchGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search platforms on IGDB (used to add consoles) */
        get: operations["searchPlatforms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent upload jobs, newest first
         * @description A job is created when the browser starts a tus upload at /api/uploads/
         *     (metadata `filename`, optional `consoleSlug`) and follows the file
         *     through extraction, review and commit.
         */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live job changes (server-sent events)
         * @description `text/event-stream`. Each change is sent as `event: job` with an
         *     UploadJob JSON in `data`. On connect the server first replays every
         *     non-terminal job, then streams changes; a comment line is sent every
         *     25 seconds to keep proxies from closing the connection.
         */
        get: operations["streamJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One upload job */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Items found in an upload, with console and kind suggestions
         * @description Available once the job reaches `review`. Ignored items (readme, .nfo…)
         *     are listed so the review can show what was set aside.
         */
        get: operations["listJobItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry extraction of an encrypted archive with its password
         * @description The password is used for this extraction only and never stored.
         */
        post: operations["submitJobPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a job and delete its uploaded data */
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview where a reviewed upload would be stored
         * @description Computes the final folder and file names (spec §5) and the duplicates
         *     against the game's current items (RF-10), without changing anything.
         *     `onDuplicate` may be left out; such items come back as `undecided`.
         */
        post: operations["planJobCommit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Store a reviewed upload in the library
         * @description Moves the items to `<console>/<game>/` with their final names, rewrites
         *     the FILE lines of .cue sheets, sends replaced duplicates to the trash and
         *     deletes the staging area (RF-11). Every duplicate needs `onDuplicate`.
         *     If anything fails, every move is undone and the job returns to review
         *     with the reason in `error`.
         */
        post: operations["commitJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consoles/{slug}/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Games of one console, by title */
        get: operations["listConsoleGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the library by title, across consoles (RF-22)
         * @description Every word must appear in the title; case and accents are ignored.
         */
        get: operations["searchLibrary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Game detail with its items (RF-21) */
        get: operations["getGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The whole game as an uncompressed zip, streamed (RF-23)
         * @description Entries are "<game folder>/<file>". The zip is built while it is sent,
         *     so it cannot be resumed; Content-Length is announced, and files over
         *     4 GB use zip64.
         */
        get: operations["downloadGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download one item (RF-23)
         * @description A single-file item is sent as is and supports HTTP Range (resumable
         *     downloads). Discs (.cue + tracks) and folder games are sent as a zip,
         *     like /games/{id}/download.
         */
        get: operations["downloadItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send every item of a game to the trash, as one entry (RF-25) */
        post: operations["trashGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{id}/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send one item to the trash (RF-25) */
        post: operations["trashItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{id}/forget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove a missing item (deleted over SMB) from the library (RF-26) */
        post: operations["forgetItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The last integrity check (it runs at start and every hour) */
        get: operations["getLibraryCheck"];
        put?: never;
        /** Run the integrity check now (it also runs every hour) */
        post: operations["checkLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/rematch/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview matching a game to another IGDB entry (RF-24)
         * @description When the new IGDB game is already in the library (same console) the
         *     games merge; items that are duplicates there come back `undecided`.
         */
        post: operations["planRematch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/rematch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Match a game to another IGDB entry, renaming its folder and files (RF-24)
         * @description Reversible like a commit. Every duplicate of a merge needs a decision.
         */
        post: operations["rematchGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The trash, newest first (RF-30) */
        get: operations["listTrash"];
        put?: never;
        post?: never;
        /** Delete everything in the trash for good */
        delete: operations["emptyTrash"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trash/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete one entry for good */
        delete: operations["deleteTrashEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trash/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Put an entry back in its game
         * @description Files take the names of the game's current title. If an item's place
         *     is taken (a duplicate was stored since), the answer is 409 unless
         *     `onConflict` is `replace`: the current item then goes to the trash.
         */
        post: operations["restoreTrashEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/{size}/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * IGDB image (cover or logo) served from the local cache
         * @description Downloaded from the IGDB image CDN on first request and cached under
         *     DATA_PATH, so the NAS keeps working offline and the browser never
         *     contacts third parties.
         */
        get: operations["getImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            checks: components["schemas"]["HealthCheck"][];
        };
        HealthCheck: {
            /** @example library-writable */
            name: string;
            ok: boolean;
            /** @description Human readable explanation when the check fails. */
            message?: string;
        };
        LoginRequest: {
            /** Format: password */
            password: string;
        };
        Session: {
            /** Format: date-time */
            expiresAt: string;
        };
        Console: {
            /** Format: int64 */
            id: number;
            /**
             * @description Folder name in the library (ES-DE style).
             * @example ps2
             */
            slug: string;
            /** @example PlayStation 2 */
            displayName: string;
            /** Format: int64 */
            igdbPlatformId?: number | null;
            /** @example 2000 */
            releaseYear?: number | null;
            /** @description IGDB image id; render with /api/images/logo_med/{logoImageId}. */
            logoImageId?: string | null;
            extensions: string[];
            sortOrder: number;
            /** @description Games with at least one item in the library. */
            gameCount: number;
            /** @description One of the six consoles the app ships with; they cannot be deleted. */
            builtIn: boolean;
            /**
             * @description How uploads are recognized: Switch title id, disc header, folder
             *     structure (PS3) or, for consoles added by the user, extension only.
             * @enum {string}
             */
            detection: "titleId" | "header" | "structure" | "extension";
        };
        MetadataGame: {
            /**
             * Format: int64
             * @description IGDB game id.
             */
            id: number;
            /** @example Mario Kart 8 Deluxe */
            name: string;
            releaseYear?: number | null;
            /** @description Render with /api/images/cover_big/{coverImageId}. */
            coverImageId?: string | null;
            summary?: string | null;
            genres: string[];
            platformIds: number[];
        };
        MetadataPlatform: {
            /**
             * Format: int64
             * @description IGDB platform id.
             */
            id: number;
            /** @example Wii U */
            name: string;
            abbreviation?: string | null;
            logoImageId?: string | null;
            releaseYear?: number | null;
        };
        /**
         * @description IGDB image size preset.
         * @enum {string}
         */
        ImageSize: "cover_small" | "cover_big" | "logo_med" | "screenshot_med";
        /**
         * @description uploading → uploaded → (extracting ⇄ needs_password) → review →
         *     committing → done; failed, cancelled and merged are terminal.
         *     Parts of a multi-volume archive go uploaded → waiting_parts; when the
         *     set is complete the first volume continues and the rest become merged.
         * @enum {string}
         */
        JobStatus: "uploading" | "uploaded" | "waiting_parts" | "merged" | "extracting" | "needs_password" | "review" | "committing" | "done" | "failed" | "cancelled";
        UploadJob: {
            /** @description Equals the tus upload id. */
            id: string;
            /** @example INSIDE-Switch-NSP-Base-Game.rar */
            fileName: string;
            /** Format: int64 */
            size: number;
            /** Format: int64 */
            received: number;
            status: components["schemas"]["JobStatus"];
            /** @description Extraction percentage while status is extracting. */
            progress?: number;
            /** @description Human readable reason (failed, or why a password is needed). */
            error?: string | null;
            /** @description Non-fatal note, e.g. archive file attributes not applied. */
            warning?: string | null;
            /** @description Slug of the console screen the upload started from. */
            originConsole?: string | null;
            /** @description Part number for multi-volume archives (1 = first). */
            volumeIndex?: number | null;
            /** @description Job (first volume) that took over this part. */
            mergedInto?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PasswordRequest: {
            /** Format: password */
            password: string;
        };
        StagedItem: {
            /**
             * @description Relative to the upload; for discs, the .cue sheet. Identifies the item in the review.
             * @example Wrapper/INSIDE [0100D2D009028000][v0].nsp
             */
            path: string;
            /**
             * @description file; disc = .cue plus its .bin tracks; folder = folder-format game (PS3), kept whole.
             * @enum {string}
             */
            shape: "file" | "disc" | "folder";
            parts: string[];
            /** Format: int64 */
            size: number;
            /** @description Junk (readme, .nfo, images) set aside; not stored in the library. */
            ignored: boolean;
            /** @description Candidate console slugs; one when the content was conclusive, empty when unknown. */
            consoles: string[];
            /** @enum {string} */
            confidence: "header" | "extension" | "none";
            suggestedKind?: components["schemas"]["ItemKind"] | null;
            /** @description Nintendo Switch title id found in the file name. */
            titleId?: string | null;
            /** @description Numeric version tag ([v196608]). */
            versionCode?: string | null;
            /** @description Human version (1.0.3), suggested as the update label. */
            displayVersion?: string | null;
            discNumber?: number | null;
        };
        /**
         * @description What a stored item is within a game folder.
         * @enum {string}
         */
        ItemKind: "base" | "update" | "dlc" | "disc";
        CommitRequest: {
            /**
             * @description Console slug.
             * @example switch
             */
            console: string;
            /** Format: int64 */
            igdbGameId: number;
            /** @description One entry per staged item that is not ignored. */
            items: components["schemas"]["CommitItem"][];
        };
        CommitItem: {
            /** @description StagedItem.path. */
            path: string;
            /** @description Leave this item out of the library (it is deleted with the staging area). */
            skip?: boolean;
            kind?: components["schemas"]["ItemKind"];
            /** @description Update version (v1.0.3) or DLC name. */
            label?: string;
            discNumber?: number;
            /**
             * @description replace sends the existing item to the trash; skip keeps it and drops this one.
             * @enum {string}
             */
            onDuplicate?: "replace" | "skip";
        };
        LibraryItem: {
            /** Format: int64 */
            id: number;
            kind: components["schemas"]["ItemKind"];
            label?: string | null;
            discNumber?: number | null;
            /**
             * @description file downloads as is (resumable); disc and folder download as a zip.
             * @enum {string}
             */
            shape: "file" | "disc" | "folder";
            /** @description Relative to the game folder; the first is the main entry. */
            files: string[];
            /** Format: int64 */
            size: number;
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description Set while a file of the item is missing from disk (deleted over SMB).
             */
            missingSince?: string | null;
        };
        GameSummary: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            igdbId: number;
            /** @description Console slug. */
            console: string;
            title: string;
            /** @description Folder inside the console folder. */
            folder: string;
            releaseYear?: number | null;
            /** @description Render with /api/images/cover_big/{coverImageId}. */
            coverImageId?: string | null;
            itemCount: number;
            /** @description Items with files missing from disk. */
            missingCount: number;
            /**
             * Format: int64
             * @description Bytes of every item in the library.
             */
            size: number;
        };
        GameDetail: components["schemas"]["GameSummary"] & {
            /**
             * @description Library-relative folder.
             * @example switch/Inside
             */
            path: string;
            summary?: string | null;
            genres: string[];
            /** @description Items in the library (not in the trash), base first. */
            items: components["schemas"]["LibraryItem"][];
        };
        ConsoleInput: {
            /**
             * @description Folder name; can only change while the console has no games.
             * @example n64
             */
            slug: string;
            /** @example Nintendo 64 */
            displayName: string;
            extensions: string[];
        };
        ConsoleCreate: components["schemas"]["ConsoleInput"] & {
            /** Format: int64 */
            igdbPlatformId: number;
        };
        ConsoleOrder: {
            /** @description Every console id, first to last. */
            ids: number[];
        };
        IntegrityReport: {
            /** Format: date-time */
            checkedAt: string;
            checked: number;
            /** @description Items found missing in this check. */
            missing: number;
            /** @description Missing items whose files are back. */
            found: number;
            /** @description Items still missing after this check. */
            missingTotal: number;
        };
        IntegrityStatus: {
            /** @description Unset until the first check has run. */
            lastCheck?: components["schemas"]["IntegrityReport"] | null;
        };
        RematchRequest: {
            /** Format: int64 */
            igdbGameId: number;
            /** @description For duplicates when merging into a game that already has the new IGDB id. */
            decisions?: components["schemas"]["ItemDecision"][];
        };
        ItemDecision: {
            /** Format: int64 */
            itemId: number;
            /**
             * @description replace sends the other game's item to the trash; skip sends this one.
             * @enum {string}
             */
            onDuplicate: "replace" | "skip";
        };
        RematchPlan: {
            console: string;
            title: string;
            /** @description Folder after the re-match. */
            folder: string;
            /**
             * Format: int64
             * @description Game that already has the new IGDB id; the games merge.
             */
            mergeInto?: number | null;
            items: components["schemas"]["RematchItem"][];
        };
        RematchItem: {
            item: components["schemas"]["LibraryItem"];
            /** @description New names. */
            files: string[];
            /** @enum {string} */
            action: "store" | "replace" | "skip" | "undecided";
            duplicate?: components["schemas"]["LibraryItem"] | null;
        };
        RematchResult: {
            /** Format: int64 */
            gameId: number;
            /** @example switch/Inside */
            path: string;
            merged: boolean;
        };
        TrashEntry: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            gameId: number;
            console: string;
            title: string;
            folder: string;
            wholeGame: boolean;
            /**
             * @description deleted by the user, or replaced by a duplicate.
             * @enum {string}
             */
            reason: "deleted" | "replaced";
            /** Format: date-time */
            trashedAt: string;
            /**
             * Format: date-time
             * @description When it is deleted for good (TRASH_RETENTION_DAYS).
             */
            expiresAt: string;
            /** Format: int64 */
            size: number;
            items: components["schemas"]["LibraryItem"][];
        };
        RestoreRequest: {
            /** @enum {string} */
            onConflict?: "replace";
        };
        RestoreResult: {
            /** Format: int64 */
            gameId: number;
            path: string;
        };
        PlannedItem: {
            path: string;
            /** @description Final names inside the game folder (a .cue sheet first, then its tracks). */
            files: string[];
            /** @enum {string} */
            action: "store" | "replace" | "skip" | "undecided";
            duplicate?: components["schemas"]["LibraryItem"] | null;
        };
        CommitPlan: {
            console: string;
            /** @description Game title used for the names. */
            title: string;
            /**
             * @description Game folder inside the console folder.
             * @example The Legend of Zelda - Tears of the Kingdom
             */
            folder: string;
            /**
             * Format: int64
             * @description Set when the game is already in the library.
             */
            gameId?: number | null;
            /** @description The game's current items. */
            existing: components["schemas"]["LibraryItem"][];
            /** @description Items that are not skipped by the user. */
            items: components["schemas"]["PlannedItem"][];
        };
        CommitResult: {
            job: components["schemas"]["UploadJob"];
            /** Format: int64 */
            gameId: number;
            /**
             * @description Library-relative game folder.
             * @example switch/Mario Kart 8 Deluxe
             */
            path: string;
            stored: number;
            replaced: number;
            skipped: number;
        };
        /** @description RFC 9457 problem details. */
        Problem: {
            type?: string;
            title: string;
            status: number;
            detail?: string;
        };
    };
    responses: {
        /** @description The resource is in a state that does not allow this operation. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing, invalid or expired session, or wrong password. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Too many login attempts from this client; retry later. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Invalid parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description IGDB failed or could not be reached. */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The operation failed; `detail` explains what happened. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description IGDB credentials are not configured. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ConsoleId: number;
        ItemId: number;
        TrashEntryId: number;
        GameId: number;
        JobId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session started; the cookie is set. */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cookie cleared. */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session is valid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listConsoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All consoles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Console"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createConsole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsoleCreate"];
            };
        };
        responses: {
            /** @description The new console. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Console"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    reorderConsoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsoleOrder"];
            };
        };
        responses: {
            /** @description Consoles in the new order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Console"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteConsole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsoleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateConsole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsoleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsoleInput"];
            };
        };
        responses: {
            /** @description The console. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Console"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    searchGames: {
        parameters: {
            query: {
                q: string;
                /** @description IGDB platform id (Console.igdbPlatformId). */
                platformId?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching games, best match first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataGame"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    searchPlatforms: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching platforms. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataPlatform"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to 100 jobs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadJob"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    streamJobEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadJob"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listJobItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Items, sorted by path. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagedItem"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    submitJobPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRequest"];
            };
        };
        responses: {
            /** @description Extraction queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cancelled job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadJob"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    planJobCommit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitRequest"];
            };
        };
        responses: {
            /** @description The plan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitPlan"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    commitJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitRequest"];
            };
        };
        responses: {
            /** @description Stored; the job is done. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listConsoleGames: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Games with at least one item in the library (trashed items do not count). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    searchLibrary: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching games, by title. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSummary"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The game. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    downloadGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The zip. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    downloadItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file, or a zip for multi-file items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                    "application/zip": string;
                };
            };
            /** @description The requested range of a single-file item. */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The requested range is not satisfiable. */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    trashGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description In the trash. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    trashItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description In the trash. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    forgetItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forgotten. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getLibraryCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The last check, if one has run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrityStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    checkLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrityReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    planRematch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RematchRequest"];
            };
        };
        responses: {
            /** @description The plan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RematchPlan"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    rematchGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RematchRequest"];
            };
        };
        responses: {
            /** @description Where the game is now. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RematchResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listTrash: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashEntry"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    emptyTrash: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Emptied. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteTrashEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TrashEntryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    restoreTrashEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TrashEntryId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RestoreRequest"];
            };
        };
        responses: {
            /** @description Restored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                size: components["schemas"]["ImageSize"];
                imageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The image. */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
        };
    };
}
