/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe and startup diagnostics
         * @description Always answers 200 while the process is up. `status` is `degraded` when
         *     a check fails (for example the library is not writable), so the UI can
         *     explain the problem instead of the container crash-looping.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a session with the shared password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the session on this device */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consoles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consoles in carousel order */
        get: operations["listConsoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search games on IGDB, optionally limited to one platform */
        get: operations["searchGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search platforms on IGDB (used to add consoles) */
        get: operations["searchPlatforms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent upload jobs, newest first
         * @description A job is created when the browser starts a tus upload at /api/uploads/
         *     (metadata `filename`, optional `consoleSlug`) and follows the file
         *     through extraction, review and commit.
         */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live job changes (server-sent events)
         * @description `text/event-stream`. Each change is sent as `event: job` with an
         *     UploadJob JSON in `data`. On connect the server first replays every
         *     non-terminal job, then streams changes; a comment line is sent every
         *     25 seconds to keep proxies from closing the connection.
         */
        get: operations["streamJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One upload job */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Items found in an upload, with console and kind suggestions
         * @description Available once the job reaches `review`. Ignored items (readme, .nfo…)
         *     are listed so the review can show what was set aside.
         */
        get: operations["listJobItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry extraction of an encrypted archive with its password
         * @description The password is used for this extraction only and never stored.
         */
        post: operations["submitJobPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a job and delete its uploaded data */
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/{size}/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * IGDB image (cover or logo) served from the local cache
         * @description Downloaded from the IGDB image CDN on first request and cached under
         *     DATA_PATH, so the NAS keeps working offline and the browser never
         *     contacts third parties.
         */
        get: operations["getImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            checks: components["schemas"]["HealthCheck"][];
        };
        HealthCheck: {
            /** @example library-writable */
            name: string;
            ok: boolean;
            /** @description Human readable explanation when the check fails. */
            message?: string;
        };
        LoginRequest: {
            /** Format: password */
            password: string;
        };
        Session: {
            /** Format: date-time */
            expiresAt: string;
        };
        Console: {
            /** Format: int64 */
            id: number;
            /**
             * @description Folder name in the library (ES-DE style).
             * @example ps2
             */
            slug: string;
            /** @example PlayStation 2 */
            displayName: string;
            /** Format: int64 */
            igdbPlatformId?: number | null;
            /** @example 2000 */
            releaseYear?: number | null;
            /** @description IGDB image id; render with /api/images/logo_med/{logoImageId}. */
            logoImageId?: string | null;
            extensions: string[];
            sortOrder: number;
        };
        MetadataGame: {
            /**
             * Format: int64
             * @description IGDB game id.
             */
            id: number;
            /** @example Mario Kart 8 Deluxe */
            name: string;
            releaseYear?: number | null;
            /** @description Render with /api/images/cover_big/{coverImageId}. */
            coverImageId?: string | null;
            summary?: string | null;
            genres: string[];
            platformIds: number[];
        };
        MetadataPlatform: {
            /**
             * Format: int64
             * @description IGDB platform id.
             */
            id: number;
            /** @example Wii U */
            name: string;
            abbreviation?: string | null;
            logoImageId?: string | null;
            releaseYear?: number | null;
        };
        /**
         * @description IGDB image size preset.
         * @enum {string}
         */
        ImageSize: "cover_small" | "cover_big" | "logo_med" | "screenshot_med";
        /**
         * @description uploading → uploaded → (extracting ⇄ needs_password) → review →
         *     committing → done; failed and cancelled are terminal.
         * @enum {string}
         */
        JobStatus: "uploading" | "uploaded" | "extracting" | "needs_password" | "review" | "committing" | "done" | "failed" | "cancelled";
        UploadJob: {
            /** @description Equals the tus upload id. */
            id: string;
            /** @example INSIDE-Switch-NSP-Base-Game.rar */
            fileName: string;
            /** Format: int64 */
            size: number;
            /** Format: int64 */
            received: number;
            status: components["schemas"]["JobStatus"];
            /** @description Extraction percentage while status is extracting. */
            progress?: number;
            /** @description Human readable reason (failed, or why a password is needed). */
            error?: string | null;
            /** @description Non-fatal note, e.g. archive file attributes not applied. */
            warning?: string | null;
            /** @description Slug of the console screen the upload started from. */
            originConsole?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PasswordRequest: {
            /** Format: password */
            password: string;
        };
        StagedItem: {
            /**
             * @description Relative to the upload; for discs, the .cue sheet. Identifies the item in the review.
             * @example Wrapper/INSIDE [0100D2D009028000][v0].nsp
             */
            path: string;
            /**
             * @description file; disc = .cue plus its .bin tracks; folder = folder-format game (PS3), kept whole.
             * @enum {string}
             */
            shape: "file" | "disc" | "folder";
            parts: string[];
            /** Format: int64 */
            size: number;
            /** @description Junk (readme, .nfo, images) set aside; not stored in the library. */
            ignored: boolean;
            /** @description Candidate console slugs; one when the content was conclusive, empty when unknown. */
            consoles: string[];
            /** @enum {string} */
            confidence: "header" | "extension" | "none";
            suggestedKind?: components["schemas"]["ItemKind"] | null;
            /** @description Nintendo Switch title id found in the file name. */
            titleId?: string | null;
            /** @description Numeric version tag ([v196608]). */
            versionCode?: string | null;
            /** @description Human version (1.0.3), suggested as the update label. */
            displayVersion?: string | null;
            discNumber?: number | null;
        };
        /**
         * @description What a stored item is within a game folder.
         * @enum {string}
         */
        ItemKind: "base" | "update" | "dlc" | "disc";
        /** @description RFC 9457 problem details. */
        Problem: {
            type?: string;
            title: string;
            status: number;
            detail?: string;
        };
    };
    responses: {
        /** @description The resource is in a state that does not allow this operation. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing, invalid or expired session, or wrong password. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Too many login attempts from this client; retry later. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Invalid parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description IGDB failed or could not be reached. */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description IGDB credentials are not configured. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        JobId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session started; the cookie is set. */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cookie cleared. */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session is valid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listConsoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All consoles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Console"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    searchGames: {
        parameters: {
            query: {
                q: string;
                /** @description IGDB platform id (Console.igdbPlatformId). */
                platformId?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching games, best match first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataGame"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    searchPlatforms: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching platforms. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataPlatform"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to 100 jobs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadJob"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    streamJobEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadJob"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listJobItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Items, sorted by path. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagedItem"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    submitJobPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRequest"];
            };
        };
        responses: {
            /** @description Extraction queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cancelled job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadJob"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                size: components["schemas"]["ImageSize"];
                imageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The image. */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
        };
    };
}
