// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlcgen

import (
	"context"
)

const deleteFiles = `-- name: DeleteFiles :exec
DELETE FROM staged_files WHERE job_id = ?
`

func (q *Queries) DeleteFiles(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, deleteFiles, jobID)
	return err
}

const insertFile = `-- name: InsertFile :exec
INSERT INTO staged_files (job_id, path, size) VALUES (?, ?, ?)
`

type InsertFileParams struct {
	JobID string
	Path  string
	Size  int64
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) error {
	_, err := q.db.ExecContext(ctx, insertFile, arg.JobID, arg.Path, arg.Size)
	return err
}

const listFiles = `-- name: ListFiles :many
SELECT path, size FROM staged_files WHERE job_id = ? ORDER BY path
`

type ListFilesRow struct {
	Path string
	Size int64
}

func (q *Queries) ListFiles(ctx context.Context, jobID string) ([]ListFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFiles, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesRow
	for rows.Next() {
		var i ListFilesRow
		if err := rows.Scan(&i.Path, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
