// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlcgen

import (
	"context"
)

const deleteItems = `-- name: DeleteItems :exec
DELETE FROM staged_items WHERE job_id = ?
`

func (q *Queries) DeleteItems(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, deleteItems, jobID)
	return err
}

const insertItem = `-- name: InsertItem :exec
INSERT INTO staged_items (job_id, path, shape, parts, size, ignored, consoles, confidence,
                          suggested_kind, title_id, version_code, display_version, disc_number)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertItemParams struct {
	JobID          string
	Path           string
	Shape          string
	Parts          string
	Size           int64
	Ignored        int64
	Consoles       string
	Confidence     string
	SuggestedKind  string
	TitleID        string
	VersionCode    string
	DisplayVersion string
	DiscNumber     int64
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) error {
	_, err := q.db.ExecContext(ctx, insertItem,
		arg.JobID,
		arg.Path,
		arg.Shape,
		arg.Parts,
		arg.Size,
		arg.Ignored,
		arg.Consoles,
		arg.Confidence,
		arg.SuggestedKind,
		arg.TitleID,
		arg.VersionCode,
		arg.DisplayVersion,
		arg.DiscNumber,
	)
	return err
}

const listItems = `-- name: ListItems :many
SELECT job_id, path, shape, parts, size, ignored, consoles, confidence, suggested_kind, title_id, version_code, display_version, disc_number FROM staged_items WHERE job_id = ? ORDER BY path
`

func (q *Queries) ListItems(ctx context.Context, jobID string) ([]StagedItem, error) {
	rows, err := q.db.QueryContext(ctx, listItems, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StagedItem
	for rows.Next() {
		var i StagedItem
		if err := rows.Scan(
			&i.JobID,
			&i.Path,
			&i.Shape,
			&i.Parts,
			&i.Size,
			&i.Ignored,
			&i.Consoles,
			&i.Confidence,
			&i.SuggestedKind,
			&i.TitleID,
			&i.VersionCode,
			&i.DisplayVersion,
			&i.DiscNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
