// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createJob = `-- name: CreateJob :exec
INSERT INTO upload_jobs (id, file_name, size, received, status, error, warning, progress, console, title, igdb_id,
                         invalid_reason, group_id, group_size, merged_into, storage_path, unassigned_origin,
                         unassigned_from, unassigned_reason, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateJobParams struct {
	ID               string
	FileName         string
	Size             int64
	Received         int64
	Status           string
	Error            string
	Warning          string
	Progress         int64
	Console          string
	Title            string
	IgdbID           sql.NullInt64
	InvalidReason    string
	GroupID          string
	GroupSize        int64
	MergedInto       string
	StoragePath      string
	UnassignedOrigin string
	UnassignedFrom   string
	UnassignedReason string
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.ExecContext(ctx, createJob,
		arg.ID,
		arg.FileName,
		arg.Size,
		arg.Received,
		arg.Status,
		arg.Error,
		arg.Warning,
		arg.Progress,
		arg.Console,
		arg.Title,
		arg.IgdbID,
		arg.InvalidReason,
		arg.GroupID,
		arg.GroupSize,
		arg.MergedInto,
		arg.StoragePath,
		arg.UnassignedOrigin,
		arg.UnassignedFrom,
		arg.UnassignedReason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, file_name, size, received, status, error, warning, progress, console, title, igdb_id, invalid_reason, group_id, group_size, merged_into, storage_path, unassigned_origin, created_at, updated_at, unassigned_from, unassigned_reason FROM upload_jobs WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (UploadJob, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i UploadJob
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Size,
		&i.Received,
		&i.Status,
		&i.Error,
		&i.Warning,
		&i.Progress,
		&i.Console,
		&i.Title,
		&i.IgdbID,
		&i.InvalidReason,
		&i.GroupID,
		&i.GroupSize,
		&i.MergedInto,
		&i.StoragePath,
		&i.UnassignedOrigin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnassignedFrom,
		&i.UnassignedReason,
	)
	return i, err
}

const jobExists = `-- name: JobExists :one
SELECT EXISTS(SELECT 1 FROM upload_jobs WHERE id = ?)
`

func (q *Queries) JobExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, jobExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGroup = `-- name: ListGroup :many
SELECT id, file_name, size, received, status, error, warning, progress, console, title, igdb_id, invalid_reason, group_id, group_size, merged_into, storage_path, unassigned_origin, created_at, updated_at, unassigned_from, unassigned_reason FROM upload_jobs WHERE group_id = ? ORDER BY created_at, id
`

func (q *Queries) ListGroup(ctx context.Context, groupID string) ([]UploadJob, error) {
	rows, err := q.db.QueryContext(ctx, listGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadJob
	for rows.Next() {
		var i UploadJob
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Size,
			&i.Received,
			&i.Status,
			&i.Error,
			&i.Warning,
			&i.Progress,
			&i.Console,
			&i.Title,
			&i.IgdbID,
			&i.InvalidReason,
			&i.GroupID,
			&i.GroupSize,
			&i.MergedInto,
			&i.StoragePath,
			&i.UnassignedOrigin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnassignedFrom,
			&i.UnassignedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, file_name, size, received, status, error, warning, progress, console, title, igdb_id, invalid_reason, group_id, group_size, merged_into, storage_path, unassigned_origin, created_at, updated_at, unassigned_from, unassigned_reason FROM upload_jobs ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListJobs(ctx context.Context, limit int64) ([]UploadJob, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadJob
	for rows.Next() {
		var i UploadJob
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Size,
			&i.Received,
			&i.Status,
			&i.Error,
			&i.Warning,
			&i.Progress,
			&i.Console,
			&i.Title,
			&i.IgdbID,
			&i.InvalidReason,
			&i.GroupID,
			&i.GroupSize,
			&i.MergedInto,
			&i.StoragePath,
			&i.UnassignedOrigin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnassignedFrom,
			&i.UnassignedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleJobs = `-- name: ListStaleJobs :many
SELECT id, file_name, size, received, status, error, warning, progress, console, title, igdb_id, invalid_reason, group_id, group_size, merged_into, storage_path, unassigned_origin, created_at, updated_at, unassigned_from, unassigned_reason FROM upload_jobs WHERE status = ? AND updated_at < ? ORDER BY updated_at
`

type ListStaleJobsParams struct {
	Status    string
	UpdatedAt string
}

func (q *Queries) ListStaleJobs(ctx context.Context, arg ListStaleJobsParams) ([]UploadJob, error) {
	rows, err := q.db.QueryContext(ctx, listStaleJobs, arg.Status, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadJob
	for rows.Next() {
		var i UploadJob
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Size,
			&i.Received,
			&i.Status,
			&i.Error,
			&i.Warning,
			&i.Progress,
			&i.Console,
			&i.Title,
			&i.IgdbID,
			&i.InvalidReason,
			&i.GroupID,
			&i.GroupSize,
			&i.MergedInto,
			&i.StoragePath,
			&i.UnassignedOrigin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnassignedFrom,
			&i.UnassignedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveJob = `-- name: SaveJob :exec
UPDATE upload_jobs
SET received = ?, status = ?, error = ?, warning = ?, progress = ?, console = ?, invalid_reason = ?,
    merged_into = ?, storage_path = ?, updated_at = ?
WHERE id = ?
`

type SaveJobParams struct {
	Received      int64
	Status        string
	Error         string
	Warning       string
	Progress      int64
	Console       string
	InvalidReason string
	MergedInto    string
	StoragePath   string
	UpdatedAt     string
	ID            string
}

func (q *Queries) SaveJob(ctx context.Context, arg SaveJobParams) error {
	_, err := q.db.ExecContext(ctx, saveJob,
		arg.Received,
		arg.Status,
		arg.Error,
		arg.Warning,
		arg.Progress,
		arg.Console,
		arg.InvalidReason,
		arg.MergedInto,
		arg.StoragePath,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
