// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createJob = `-- name: CreateJob :exec
INSERT INTO upload_jobs (id, file_name, size, received, status, error, origin_console, storage_path,
                         progress, warning, volume_set, volume_index, merged_into, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateJobParams struct {
	ID            string
	FileName      string
	Size          int64
	Received      int64
	Status        string
	Error         string
	OriginConsole sql.NullString
	StoragePath   string
	Progress      int64
	Warning       string
	VolumeSet     string
	VolumeIndex   int64
	MergedInto    string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.ExecContext(ctx, createJob,
		arg.ID,
		arg.FileName,
		arg.Size,
		arg.Received,
		arg.Status,
		arg.Error,
		arg.OriginConsole,
		arg.StoragePath,
		arg.Progress,
		arg.Warning,
		arg.VolumeSet,
		arg.VolumeIndex,
		arg.MergedInto,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, file_name, size, received, status, error, origin_console, storage_path, created_at, updated_at, progress, warning, volume_set, volume_index, merged_into FROM upload_jobs WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (UploadJob, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i UploadJob
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Size,
		&i.Received,
		&i.Status,
		&i.Error,
		&i.OriginConsole,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Progress,
		&i.Warning,
		&i.VolumeSet,
		&i.VolumeIndex,
		&i.MergedInto,
	)
	return i, err
}

const jobExists = `-- name: JobExists :one
SELECT EXISTS(SELECT 1 FROM upload_jobs WHERE id = ?)
`

func (q *Queries) JobExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, jobExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, file_name, size, received, status, error, origin_console, storage_path, created_at, updated_at, progress, warning, volume_set, volume_index, merged_into FROM upload_jobs ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListJobs(ctx context.Context, limit int64) ([]UploadJob, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadJob
	for rows.Next() {
		var i UploadJob
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Size,
			&i.Received,
			&i.Status,
			&i.Error,
			&i.OriginConsole,
			&i.StoragePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Progress,
			&i.Warning,
			&i.VolumeSet,
			&i.VolumeIndex,
			&i.MergedInto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleJobs = `-- name: ListStaleJobs :many
SELECT id, file_name, size, received, status, error, origin_console, storage_path, created_at, updated_at, progress, warning, volume_set, volume_index, merged_into FROM upload_jobs WHERE status = ? AND updated_at < ? ORDER BY updated_at
`

type ListStaleJobsParams struct {
	Status    string
	UpdatedAt string
}

func (q *Queries) ListStaleJobs(ctx context.Context, arg ListStaleJobsParams) ([]UploadJob, error) {
	rows, err := q.db.QueryContext(ctx, listStaleJobs, arg.Status, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadJob
	for rows.Next() {
		var i UploadJob
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Size,
			&i.Received,
			&i.Status,
			&i.Error,
			&i.OriginConsole,
			&i.StoragePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Progress,
			&i.Warning,
			&i.VolumeSet,
			&i.VolumeIndex,
			&i.MergedInto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitingParts = `-- name: ListWaitingParts :many
SELECT id, file_name, size, received, status, error, origin_console, storage_path, created_at, updated_at, progress, warning, volume_set, volume_index, merged_into FROM upload_jobs WHERE volume_set = ? AND status = 'waiting_parts' ORDER BY volume_index
`

func (q *Queries) ListWaitingParts(ctx context.Context, volumeSet string) ([]UploadJob, error) {
	rows, err := q.db.QueryContext(ctx, listWaitingParts, volumeSet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadJob
	for rows.Next() {
		var i UploadJob
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Size,
			&i.Received,
			&i.Status,
			&i.Error,
			&i.OriginConsole,
			&i.StoragePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Progress,
			&i.Warning,
			&i.VolumeSet,
			&i.VolumeIndex,
			&i.MergedInto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveJob = `-- name: SaveJob :exec
UPDATE upload_jobs
SET received = ?, status = ?, error = ?, storage_path = ?, progress = ?, warning = ?,
    volume_set = ?, volume_index = ?, merged_into = ?, updated_at = ?
WHERE id = ?
`

type SaveJobParams struct {
	Received    int64
	Status      string
	Error       string
	StoragePath string
	Progress    int64
	Warning     string
	VolumeSet   string
	VolumeIndex int64
	MergedInto  string
	UpdatedAt   string
	ID          string
}

func (q *Queries) SaveJob(ctx context.Context, arg SaveJobParams) error {
	_, err := q.db.ExecContext(ctx, saveJob,
		arg.Received,
		arg.Status,
		arg.Error,
		arg.StoragePath,
		arg.Progress,
		arg.Warning,
		arg.VolumeSet,
		arg.VolumeIndex,
		arg.MergedInto,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
