// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Console struct {
	ID             int64
	Slug           string
	DisplayName    string
	IgdbPlatformID sql.NullInt64
	ReleaseYear    sql.NullInt64
	LogoImageID    sql.NullString
	Extensions     string
	DetectorKey    sql.NullString
	SortOrder      int64
	CreatedAt      string
}

type Game struct {
	ID           int64
	ConsoleID    int64
	IgdbID       int64
	Title        string
	Folder       string
	ReleaseYear  sql.NullInt64
	CoverImageID sql.NullString
	Summary      sql.NullString
	Genres       string
	CreatedAt    string
	UpdatedAt    string
}

type GameItem struct {
	ID           int64
	GameID       int64
	Kind         string
	Label        string
	DiscNumber   int64
	Shape        string
	Files        string
	Size         int64
	TitleID      string
	SourceJob    string
	CreatedAt    string
	TrashEntryID sql.NullInt64
	MissingSince sql.NullString
}

type LibraryOperation struct {
	ID          string
	Source      string
	Moves       string
	CreatedDirs string
	CreatedAt   string
}

type StagedItem struct {
	JobID          string
	Path           string
	Shape          string
	Parts          string
	Size           int64
	Ignored        int64
	Consoles       string
	Confidence     string
	SuggestedKind  string
	TitleID        string
	VersionCode    string
	DisplayVersion string
	DiscNumber     int64
}

type TrashEntry struct {
	ID        int64
	GameID    int64
	WholeGame int64
	Reason    string
	Dir       string
	TrashedAt string
}

type UploadJob struct {
	ID            string
	FileName      string
	Size          int64
	Received      int64
	Status        string
	Error         string
	OriginConsole sql.NullString
	StoragePath   string
	CreatedAt     string
	UpdatedAt     string
	Progress      int64
	Warning       string
	VolumeSet     string
	VolumeIndex   int64
	MergedInto    string
}
