import type { MetadataPorts } from '../../application/ports'
import type { MetadataGame } from '../../domain/types'
import catalog from './catalog.json'

/** The fixed IGDB catalog of the demo (RF-61), generated by `task demo-catalog`. */
export const demoCatalog: { platforms: DemoPlatform[]; games: MetadataGame[] } = catalog

export interface DemoPlatform {
  id: number
  name: string
  abbreviation: string
  logoImageId: string
  releaseYear: number
}

/** Lower case without accents: "Ōkami" matches "okami". */
export function fold(text: string): string {
  return text.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase()
}

/** Exact name, then prefix, then whole word, then anywhere (RF-20a). */
function score(name: string, query: string): number {
  if (name === query) return 3
  if (name.startsWith(query)) return 2
  if (new RegExp(`\\b${query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`).test(name)) return 1
  return 0
}

/**
 * Metadata without backend: suggestions from the fixed catalog, images from
 * IGDB's CDN (the demo has no image cache; RF-61).
 */
export function createMetadataDemo(): MetadataPorts {
  return {
    searchGames: (query, platformId, limit = 10) => {
      const q = fold(query.trim())
      const words = q.split(/\s+/).filter(Boolean)
      const found = demoCatalog.games
        .filter((g) => platformId === undefined || g.platformIds.includes(platformId))
        .map((g) => ({ g, name: fold(g.name) }))
        .filter(({ name }) => words.length > 0 && words.every((w) => name.includes(w)))
        .sort((a, b) => score(b.name, q) - score(a.name, q) || a.name.localeCompare(b.name))
        .slice(0, limit)
        .map(({ g }) => g)
      return Promise.resolve(found)
    },
    status: () => Promise.resolve({ configured: true }),
    imageUrl: (size, imageId) =>
      `https://images.igdb.com/igdb/image/upload/t_${size}/${encodeURIComponent(imageId)}.${size.startsWith('logo') ? 'png' : 'jpg'}`,
  }
}
