// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consoles.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const listConsoles = `-- name: ListConsoles :many
SELECT id, slug, display_name, igdb_platform_id, release_year, extensions, sort_order
FROM consoles
ORDER BY sort_order, id
`

type ListConsolesRow struct {
	ID             int64
	Slug           string
	DisplayName    string
	IgdbPlatformID sql.NullInt64
	ReleaseYear    sql.NullInt64
	Extensions     string
	SortOrder      int64
}

func (q *Queries) ListConsoles(ctx context.Context) ([]ListConsolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listConsoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConsolesRow
	for rows.Next() {
		var i ListConsolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.IgdbPlatformID,
			&i.ReleaseYear,
			&i.Extensions,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
