// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consoles.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const addConsoleExtension = `-- name: AddConsoleExtension :exec
INSERT OR IGNORE INTO console_extensions (slug, extension) VALUES (?, ?)
`

type AddConsoleExtensionParams struct {
	Slug      string
	Extension string
}

func (q *Queries) AddConsoleExtension(ctx context.Context, arg AddConsoleExtensionParams) error {
	_, err := q.db.ExecContext(ctx, addConsoleExtension, arg.Slug, arg.Extension)
	return err
}

const countGamesByConsole = `-- name: CountGamesByConsole :many
SELECT g.console, COUNT(DISTINCT g.id) AS games
FROM games g
JOIN game_items i ON i.game_id = g.id AND i.trash_entry_id IS NULL
GROUP BY g.console
`

type CountGamesByConsoleRow struct {
	Console string
	Games   int64
}

// Games with at least one file outside the trash.
func (q *Queries) CountGamesByConsole(ctx context.Context) ([]CountGamesByConsoleRow, error) {
	rows, err := q.db.QueryContext(ctx, countGamesByConsole)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGamesByConsoleRow
	for rows.Next() {
		var i CountGamesByConsoleRow
		if err := rows.Scan(&i.Console, &i.Games); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsoleExtensions = `-- name: ListConsoleExtensions :many
SELECT slug, extension FROM console_extensions ORDER BY slug, rowid
`

func (q *Queries) ListConsoleExtensions(ctx context.Context) ([]ConsoleExtension, error) {
	rows, err := q.db.QueryContext(ctx, listConsoleExtensions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsoleExtension
	for rows.Next() {
		var i ConsoleExtension
		if err := rows.Scan(&i.Slug, &i.Extension); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsoleItemFiles = `-- name: ListConsoleItemFiles :many
SELECT i.file FROM game_items i JOIN games g ON g.id = i.game_id WHERE g.console = ?
`

func (q *Queries) ListConsoleItemFiles(ctx context.Context, console string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listConsoleItemFiles, console)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file string
		if err := rows.Scan(&file); err != nil {
			return nil, err
		}
		items = append(items, file)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsoleSettings = `-- name: ListConsoleSettings :many
SELECT slug, display_name, sort_order, logo_image_id, release_year FROM console_settings
`

func (q *Queries) ListConsoleSettings(ctx context.Context) ([]ConsoleSetting, error) {
	rows, err := q.db.QueryContext(ctx, listConsoleSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsoleSetting
	for rows.Next() {
		var i ConsoleSetting
		if err := rows.Scan(
			&i.Slug,
			&i.DisplayName,
			&i.SortOrder,
			&i.LogoImageID,
			&i.ReleaseYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeConsoleExtension = `-- name: RemoveConsoleExtension :exec
DELETE FROM console_extensions WHERE slug = ? AND extension = ?
`

type RemoveConsoleExtensionParams struct {
	Slug      string
	Extension string
}

func (q *Queries) RemoveConsoleExtension(ctx context.Context, arg RemoveConsoleExtensionParams) error {
	_, err := q.db.ExecContext(ctx, removeConsoleExtension, arg.Slug, arg.Extension)
	return err
}

const setConsoleDisplayName = `-- name: SetConsoleDisplayName :exec
UPDATE console_settings SET display_name = ? WHERE slug = ?
`

type SetConsoleDisplayNameParams struct {
	DisplayName sql.NullString
	Slug        string
}

func (q *Queries) SetConsoleDisplayName(ctx context.Context, arg SetConsoleDisplayNameParams) error {
	_, err := q.db.ExecContext(ctx, setConsoleDisplayName, arg.DisplayName, arg.Slug)
	return err
}

const setConsolePlatformMetadata = `-- name: SetConsolePlatformMetadata :exec
UPDATE console_settings
SET logo_image_id = ?1,
    release_year  = COALESCE(?2, release_year)
WHERE slug = ?3
`

type SetConsolePlatformMetadataParams struct {
	LogoImageID sql.NullString
	ReleaseYear sql.NullInt64
	Slug        string
}

func (q *Queries) SetConsolePlatformMetadata(ctx context.Context, arg SetConsolePlatformMetadataParams) error {
	_, err := q.db.ExecContext(ctx, setConsolePlatformMetadata, arg.LogoImageID, arg.ReleaseYear, arg.Slug)
	return err
}

const upsertConsoleOrder = `-- name: UpsertConsoleOrder :exec
INSERT INTO console_settings (slug, sort_order) VALUES (?, ?)
ON CONFLICT (slug) DO UPDATE SET sort_order = excluded.sort_order
`

type UpsertConsoleOrderParams struct {
	Slug      string
	SortOrder int64
}

func (q *Queries) UpsertConsoleOrder(ctx context.Context, arg UpsertConsoleOrderParams) error {
	_, err := q.db.ExecContext(ctx, upsertConsoleOrder, arg.Slug, arg.SortOrder)
	return err
}
