// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteOperation = `-- name: DeleteOperation :exec
DELETE FROM library_operations WHERE id = ?
`

func (q *Queries) DeleteOperation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteOperation, id)
	return err
}

const findGameByIGDB = `-- name: FindGameByIGDB :one
SELECT id, console_id, igdb_id, title, folder, release_year, cover_image_id, summary, genres, created_at, updated_at
FROM games
WHERE console_id = ? AND igdb_id = ?
`

type FindGameByIGDBParams struct {
	ConsoleID int64
	IgdbID    int64
}

func (q *Queries) FindGameByIGDB(ctx context.Context, arg FindGameByIGDBParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, findGameByIGDB, arg.ConsoleID, arg.IgdbID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.ConsoleID,
		&i.IgdbID,
		&i.Title,
		&i.Folder,
		&i.ReleaseYear,
		&i.CoverImageID,
		&i.Summary,
		&i.Genres,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const folderTaken = `-- name: FolderTaken :one
SELECT EXISTS (SELECT 1 FROM games WHERE console_id = ? AND folder = ? COLLATE NOCASE)
`

type FolderTakenParams struct {
	ConsoleID int64
	Folder    string
}

func (q *Queries) FolderTaken(ctx context.Context, arg FolderTakenParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, folderTaken, arg.ConsoleID, arg.Folder)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasItemsFromSource = `-- name: HasItemsFromSource :one
SELECT EXISTS (SELECT 1 FROM game_items WHERE source_job = ?)
`

func (q *Queries) HasItemsFromSource(ctx context.Context, sourceJob string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasItemsFromSource, sourceJob)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertGame = `-- name: InsertGame :one
INSERT INTO games (console_id, igdb_id, title, folder, release_year, cover_image_id, summary, genres, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertGameParams struct {
	ConsoleID    int64
	IgdbID       int64
	Title        string
	Folder       string
	ReleaseYear  sql.NullInt64
	CoverImageID sql.NullString
	Summary      sql.NullString
	Genres       string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) InsertGame(ctx context.Context, arg InsertGameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertGame,
		arg.ConsoleID,
		arg.IgdbID,
		arg.Title,
		arg.Folder,
		arg.ReleaseYear,
		arg.CoverImageID,
		arg.Summary,
		arg.Genres,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertGameItem = `-- name: InsertGameItem :exec
INSERT INTO game_items (game_id, kind, label, disc_number, shape, files, size, title_id, source_job, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertGameItemParams struct {
	GameID     int64
	Kind       string
	Label      string
	DiscNumber int64
	Shape      string
	Files      string
	Size       int64
	TitleID    string
	SourceJob  string
	CreatedAt  string
}

func (q *Queries) InsertGameItem(ctx context.Context, arg InsertGameItemParams) error {
	_, err := q.db.ExecContext(ctx, insertGameItem,
		arg.GameID,
		arg.Kind,
		arg.Label,
		arg.DiscNumber,
		arg.Shape,
		arg.Files,
		arg.Size,
		arg.TitleID,
		arg.SourceJob,
		arg.CreatedAt,
	)
	return err
}

const insertOperation = `-- name: InsertOperation :exec
INSERT INTO library_operations (id, source, moves, created_dirs, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertOperationParams struct {
	ID          string
	Source      string
	Moves       string
	CreatedDirs string
	CreatedAt   string
}

func (q *Queries) InsertOperation(ctx context.Context, arg InsertOperationParams) error {
	_, err := q.db.ExecContext(ctx, insertOperation,
		arg.ID,
		arg.Source,
		arg.Moves,
		arg.CreatedDirs,
		arg.CreatedAt,
	)
	return err
}

const listGameItems = `-- name: ListGameItems :many
SELECT id, game_id, kind, label, disc_number, shape, files, size, title_id, source_job, created_at, trashed_at, trash_dir
FROM game_items
WHERE game_id = ?
ORDER BY id
`

func (q *Queries) ListGameItems(ctx context.Context, gameID int64) ([]GameItem, error) {
	rows, err := q.db.QueryContext(ctx, listGameItems, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameItem
	for rows.Next() {
		var i GameItem
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Kind,
			&i.Label,
			&i.DiscNumber,
			&i.Shape,
			&i.Files,
			&i.Size,
			&i.TitleID,
			&i.SourceJob,
			&i.CreatedAt,
			&i.TrashedAt,
			&i.TrashDir,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperations = `-- name: ListOperations :many
SELECT id, source, moves, created_dirs, created_at
FROM library_operations
ORDER BY created_at, id
`

func (q *Queries) ListOperations(ctx context.Context) ([]LibraryOperation, error) {
	rows, err := q.db.QueryContext(ctx, listOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LibraryOperation
	for rows.Next() {
		var i LibraryOperation
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Moves,
			&i.CreatedDirs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trashGameItem = `-- name: TrashGameItem :exec
UPDATE game_items
SET trashed_at = ?, trash_dir = ?
WHERE id = ? AND trashed_at IS NULL
`

type TrashGameItemParams struct {
	TrashedAt sql.NullString
	TrashDir  string
	ID        int64
}

func (q *Queries) TrashGameItem(ctx context.Context, arg TrashGameItemParams) error {
	_, err := q.db.ExecContext(ctx, trashGameItem, arg.TrashedAt, arg.TrashDir, arg.ID)
	return err
}

const updateGameMetadata = `-- name: UpdateGameMetadata :exec
UPDATE games
SET title = ?, release_year = ?, cover_image_id = ?, summary = ?, genres = ?, updated_at = ?
WHERE id = ?
`

type UpdateGameMetadataParams struct {
	Title        string
	ReleaseYear  sql.NullInt64
	CoverImageID sql.NullString
	Summary      sql.NullString
	Genres       string
	UpdatedAt    string
	ID           int64
}

func (q *Queries) UpdateGameMetadata(ctx context.Context, arg UpdateGameMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateGameMetadata,
		arg.Title,
		arg.ReleaseYear,
		arg.CoverImageID,
		arg.Summary,
		arg.Genres,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
