// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const clearScanPending = `-- name: ClearScanPending :exec
DELETE FROM scan_pending
`

func (q *Queries) ClearScanPending(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearScanPending)
	return err
}

const countGameItems = `-- name: CountGameItems :one
SELECT COUNT(*) FROM game_items WHERE game_id = ?
`

func (q *Queries) CountGameItems(ctx context.Context, gameID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGameItems, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games WHERE id = ?
`

func (q *Queries) DeleteGame(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGame, id)
	return err
}

const deleteGameItem = `-- name: DeleteGameItem :exec
DELETE FROM game_items WHERE id = ?
`

func (q *Queries) DeleteGameItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGameItem, id)
	return err
}

const deleteOperation = `-- name: DeleteOperation :exec
DELETE FROM library_operations WHERE id = ?
`

func (q *Queries) DeleteOperation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteOperation, id)
	return err
}

const deleteTrashEntry = `-- name: DeleteTrashEntry :exec
DELETE FROM trash_entries WHERE id = ?
`

func (q *Queries) DeleteTrashEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrashEntry, id)
	return err
}

const deleteUnassigned = `-- name: DeleteUnassigned :exec
DELETE FROM unassigned_files WHERE id = ?
`

func (q *Queries) DeleteUnassigned(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUnassigned, id)
	return err
}

const getGame = `-- name: GetGame :one
SELECT id, console, title, folder, igdb_id, release_year, cover_image_id, summary, genres, created_at, updated_at
FROM games
WHERE id = ?
`

func (q *Queries) GetGame(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Console,
		&i.Title,
		&i.Folder,
		&i.IgdbID,
		&i.ReleaseYear,
		&i.CoverImageID,
		&i.Summary,
		&i.Genres,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameByFolder = `-- name: GetGameByFolder :one
SELECT id, console, title, folder, igdb_id, release_year, cover_image_id, summary, genres, created_at, updated_at
FROM games
WHERE console = ? AND folder = ? COLLATE NOCASE
`

type GetGameByFolderParams struct {
	Console string
	Folder  string
}

func (q *Queries) GetGameByFolder(ctx context.Context, arg GetGameByFolderParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameByFolder, arg.Console, arg.Folder)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Console,
		&i.Title,
		&i.Folder,
		&i.IgdbID,
		&i.ReleaseYear,
		&i.CoverImageID,
		&i.Summary,
		&i.Genres,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameItem = `-- name: GetGameItem :one
SELECT id, game_id, kind, label, file, size, source_job, created_at, trash_entry_id
FROM game_items
WHERE id = ?
`

func (q *Queries) GetGameItem(ctx context.Context, id int64) (GameItem, error) {
	row := q.db.QueryRowContext(ctx, getGameItem, id)
	var i GameItem
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Kind,
		&i.Label,
		&i.File,
		&i.Size,
		&i.SourceJob,
		&i.CreatedAt,
		&i.TrashEntryID,
	)
	return i, err
}

const getTrashEntry = `-- name: GetTrashEntry :one
SELECT id, game_id, whole_game, reason, dir, trashed_at FROM trash_entries WHERE id = ?
`

func (q *Queries) GetTrashEntry(ctx context.Context, id int64) (TrashEntry, error) {
	row := q.db.QueryRowContext(ctx, getTrashEntry, id)
	var i TrashEntry
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.WholeGame,
		&i.Reason,
		&i.Dir,
		&i.TrashedAt,
	)
	return i, err
}

const getUnassigned = `-- name: GetUnassigned :one
SELECT id, path, origin, reason, size, arrived_at, trash_entry_id, console, igdb_id, job_id
FROM unassigned_files
WHERE id = ?
`

func (q *Queries) GetUnassigned(ctx context.Context, id int64) (UnassignedFile, error) {
	row := q.db.QueryRowContext(ctx, getUnassigned, id)
	var i UnassignedFile
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Origin,
		&i.Reason,
		&i.Size,
		&i.ArrivedAt,
		&i.TrashEntryID,
		&i.Console,
		&i.IgdbID,
		&i.JobID,
	)
	return i, err
}

const hasItemsFromSource = `-- name: HasItemsFromSource :one
SELECT EXISTS (SELECT 1 FROM game_items WHERE source_job = ?)
`

func (q *Queries) HasItemsFromSource(ctx context.Context, sourceJob string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasItemsFromSource, sourceJob)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertGame = `-- name: InsertGame :one
INSERT INTO games (console, title, folder, igdb_id, release_year, cover_image_id, summary, genres, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertGameParams struct {
	Console      string
	Title        string
	Folder       string
	IgdbID       sql.NullInt64
	ReleaseYear  sql.NullInt64
	CoverImageID sql.NullString
	Summary      sql.NullString
	Genres       string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) InsertGame(ctx context.Context, arg InsertGameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertGame,
		arg.Console,
		arg.Title,
		arg.Folder,
		arg.IgdbID,
		arg.ReleaseYear,
		arg.CoverImageID,
		arg.Summary,
		arg.Genres,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertGameItem = `-- name: InsertGameItem :one
INSERT INTO game_items (game_id, kind, label, file, size, source_job, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertGameItemParams struct {
	GameID    int64
	Kind      string
	Label     string
	File      string
	Size      int64
	SourceJob string
	CreatedAt string
}

func (q *Queries) InsertGameItem(ctx context.Context, arg InsertGameItemParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertGameItem,
		arg.GameID,
		arg.Kind,
		arg.Label,
		arg.File,
		arg.Size,
		arg.SourceJob,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertOperation = `-- name: InsertOperation :exec
INSERT INTO library_operations (id, source, moves, created_dirs, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertOperationParams struct {
	ID          string
	Source      string
	Moves       string
	CreatedDirs string
	CreatedAt   string
}

func (q *Queries) InsertOperation(ctx context.Context, arg InsertOperationParams) error {
	_, err := q.db.ExecContext(ctx, insertOperation,
		arg.ID,
		arg.Source,
		arg.Moves,
		arg.CreatedDirs,
		arg.CreatedAt,
	)
	return err
}

const insertScanPending = `-- name: InsertScanPending :exec
INSERT INTO scan_pending (path, size, mod_time) VALUES (?, ?, ?)
`

type InsertScanPendingParams struct {
	Path    string
	Size    int64
	ModTime string
}

func (q *Queries) InsertScanPending(ctx context.Context, arg InsertScanPendingParams) error {
	_, err := q.db.ExecContext(ctx, insertScanPending, arg.Path, arg.Size, arg.ModTime)
	return err
}

const insertTrashEntry = `-- name: InsertTrashEntry :one
INSERT INTO trash_entries (game_id, whole_game, reason, dir, trashed_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type InsertTrashEntryParams struct {
	GameID    sql.NullInt64
	WholeGame int64
	Reason    string
	Dir       string
	TrashedAt string
}

func (q *Queries) InsertTrashEntry(ctx context.Context, arg InsertTrashEntryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTrashEntry,
		arg.GameID,
		arg.WholeGame,
		arg.Reason,
		arg.Dir,
		arg.TrashedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertUnassigned = `-- name: InsertUnassigned :one
INSERT INTO unassigned_files (path, origin, reason, size, arrived_at, trash_entry_id, console, igdb_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertUnassignedParams struct {
	Path         string
	Origin       string
	Reason       string
	Size         int64
	ArrivedAt    string
	TrashEntryID sql.NullInt64
	Console      string
	IgdbID       sql.NullInt64
}

func (q *Queries) InsertUnassigned(ctx context.Context, arg InsertUnassignedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertUnassigned,
		arg.Path,
		arg.Origin,
		arg.Reason,
		arg.Size,
		arg.ArrivedAt,
		arg.TrashEntryID,
		arg.Console,
		arg.IgdbID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listGameItems = `-- name: ListGameItems :many
SELECT id, game_id, kind, label, file, size, source_job, created_at, trash_entry_id
FROM game_items
WHERE game_id = ?
ORDER BY id
`

func (q *Queries) ListGameItems(ctx context.Context, gameID int64) ([]GameItem, error) {
	rows, err := q.db.QueryContext(ctx, listGameItems, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameItem
	for rows.Next() {
		var i GameItem
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Kind,
			&i.Label,
			&i.File,
			&i.Size,
			&i.SourceJob,
			&i.CreatedAt,
			&i.TrashEntryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameSummaries = `-- name: ListGameSummaries :many
SELECT g.id, g.console, g.igdb_id, g.title, g.folder, g.release_year, g.cover_image_id,
       COUNT(i.id) AS item_count, CAST(TOTAL(i.size) AS INTEGER) AS size
FROM games g
JOIN game_items i ON i.game_id = g.id AND i.trash_entry_id IS NULL
GROUP BY g.id
ORDER BY g.title COLLATE NOCASE, g.id
`

type ListGameSummariesRow struct {
	ID           int64
	Console      string
	IgdbID       sql.NullInt64
	Title        string
	Folder       string
	ReleaseYear  sql.NullInt64
	CoverImageID sql.NullString
	ItemCount    int64
	Size         int64
}

// Games with at least one file outside the trash, by title.
func (q *Queries) ListGameSummaries(ctx context.Context) ([]ListGameSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGameSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGameSummariesRow
	for rows.Next() {
		var i ListGameSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Console,
			&i.IgdbID,
			&i.Title,
			&i.Folder,
			&i.ReleaseYear,
			&i.CoverImageID,
			&i.ItemCount,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryFiles = `-- name: ListLibraryFiles :many
SELECT i.id, i.game_id, g.console, g.folder, i.file
FROM game_items i
JOIN games g ON g.id = i.game_id
WHERE i.trash_entry_id IS NULL
`

type ListLibraryFilesRow struct {
	ID      int64
	GameID  int64
	Console string
	Folder  string
	File    string
}

func (q *Queries) ListLibraryFiles(ctx context.Context) ([]ListLibraryFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLibraryFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLibraryFilesRow
	for rows.Next() {
		var i ListLibraryFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Console,
			&i.Folder,
			&i.File,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperations = `-- name: ListOperations :many
SELECT id, source, moves, created_dirs, created_at
FROM library_operations
ORDER BY created_at, id
`

func (q *Queries) ListOperations(ctx context.Context) ([]LibraryOperation, error) {
	rows, err := q.db.QueryContext(ctx, listOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LibraryOperation
	for rows.Next() {
		var i LibraryOperation
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Moves,
			&i.CreatedDirs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanPending = `-- name: ListScanPending :many
SELECT path, size, mod_time FROM scan_pending
`

func (q *Queries) ListScanPending(ctx context.Context) ([]ScanPending, error) {
	rows, err := q.db.QueryContext(ctx, listScanPending)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanPending
	for rows.Next() {
		var i ScanPending
		if err := rows.Scan(&i.Path, &i.Size, &i.ModTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashEntries = `-- name: ListTrashEntries :many
SELECT id, game_id, whole_game, reason, dir, trashed_at FROM trash_entries ORDER BY trashed_at DESC, id DESC
`

func (q *Queries) ListTrashEntries(ctx context.Context) ([]TrashEntry, error) {
	rows, err := q.db.QueryContext(ctx, listTrashEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrashEntry
	for rows.Next() {
		var i TrashEntry
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.WholeGame,
			&i.Reason,
			&i.Dir,
			&i.TrashedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashItems = `-- name: ListTrashItems :many
SELECT id, game_id, kind, label, file, size, source_job, created_at, trash_entry_id
FROM game_items
WHERE trash_entry_id IS NOT NULL
ORDER BY id
`

func (q *Queries) ListTrashItems(ctx context.Context) ([]GameItem, error) {
	rows, err := q.db.QueryContext(ctx, listTrashItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameItem
	for rows.Next() {
		var i GameItem
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Kind,
			&i.Label,
			&i.File,
			&i.Size,
			&i.SourceJob,
			&i.CreatedAt,
			&i.TrashEntryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashUnassigned = `-- name: ListTrashUnassigned :many
SELECT id, path, origin, reason, size, arrived_at, trash_entry_id, console, igdb_id, job_id
FROM unassigned_files
WHERE trash_entry_id IS NOT NULL
ORDER BY id
`

func (q *Queries) ListTrashUnassigned(ctx context.Context) ([]UnassignedFile, error) {
	rows, err := q.db.QueryContext(ctx, listTrashUnassigned)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnassignedFile
	for rows.Next() {
		var i UnassignedFile
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Origin,
			&i.Reason,
			&i.Size,
			&i.ArrivedAt,
			&i.TrashEntryID,
			&i.Console,
			&i.IgdbID,
			&i.JobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassigned = `-- name: ListUnassigned :many
SELECT id, path, origin, reason, size, arrived_at, trash_entry_id, console, igdb_id, job_id
FROM unassigned_files
WHERE trash_entry_id IS NULL
ORDER BY arrived_at DESC, id DESC
`

func (q *Queries) ListUnassigned(ctx context.Context) ([]UnassignedFile, error) {
	rows, err := q.db.QueryContext(ctx, listUnassigned)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnassignedFile
	for rows.Next() {
		var i UnassignedFile
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Origin,
			&i.Reason,
			&i.Size,
			&i.ArrivedAt,
			&i.TrashEntryID,
			&i.Console,
			&i.IgdbID,
			&i.JobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveGameItems = `-- name: MoveGameItems :exec
UPDATE game_items SET game_id = ?1 WHERE game_id = ?2
`

type MoveGameItemsParams struct {
	ToGame   int64
	FromGame int64
}

func (q *Queries) MoveGameItems(ctx context.Context, arg MoveGameItemsParams) error {
	_, err := q.db.ExecContext(ctx, moveGameItems, arg.ToGame, arg.FromGame)
	return err
}

const moveTrashEntries = `-- name: MoveTrashEntries :exec
UPDATE trash_entries SET game_id = ?1 WHERE game_id = ?2
`

type MoveTrashEntriesParams struct {
	ToGame   sql.NullInt64
	FromGame sql.NullInt64
}

func (q *Queries) MoveTrashEntries(ctx context.Context, arg MoveTrashEntriesParams) error {
	_, err := q.db.ExecContext(ctx, moveTrashEntries, arg.ToGame, arg.FromGame)
	return err
}

const releaseUnassignedJob = `-- name: ReleaseUnassignedJob :exec
UPDATE unassigned_files SET job_id = '' WHERE job_id = ?
`

func (q *Queries) ReleaseUnassignedJob(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, releaseUnassignedJob, jobID)
	return err
}

const setItemTrash = `-- name: SetItemTrash :exec
UPDATE game_items SET trash_entry_id = ? WHERE id = ?
`

type SetItemTrashParams struct {
	TrashEntryID sql.NullInt64
	ID           int64
}

func (q *Queries) SetItemTrash(ctx context.Context, arg SetItemTrashParams) error {
	_, err := q.db.ExecContext(ctx, setItemTrash, arg.TrashEntryID, arg.ID)
	return err
}

const setUnassignedJob = `-- name: SetUnassignedJob :exec
UPDATE unassigned_files SET job_id = ? WHERE id = ?
`

type SetUnassignedJobParams struct {
	JobID string
	ID    int64
}

func (q *Queries) SetUnassignedJob(ctx context.Context, arg SetUnassignedJobParams) error {
	_, err := q.db.ExecContext(ctx, setUnassignedJob, arg.JobID, arg.ID)
	return err
}

const setUnassignedPlace = `-- name: SetUnassignedPlace :exec
UPDATE unassigned_files SET path = ?, trash_entry_id = ? WHERE id = ?
`

type SetUnassignedPlaceParams struct {
	Path         string
	TrashEntryID sql.NullInt64
	ID           int64
}

func (q *Queries) SetUnassignedPlace(ctx context.Context, arg SetUnassignedPlaceParams) error {
	_, err := q.db.ExecContext(ctx, setUnassignedPlace, arg.Path, arg.TrashEntryID, arg.ID)
	return err
}

const updateGame = `-- name: UpdateGame :exec
UPDATE games
SET console = ?, title = ?, folder = ?, igdb_id = ?, release_year = ?, cover_image_id = ?, summary = ?, genres = ?, updated_at = ?
WHERE id = ?
`

type UpdateGameParams struct {
	Console      string
	Title        string
	Folder       string
	IgdbID       sql.NullInt64
	ReleaseYear  sql.NullInt64
	CoverImageID sql.NullString
	Summary      sql.NullString
	Genres       string
	UpdatedAt    string
	ID           int64
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) error {
	_, err := q.db.ExecContext(ctx, updateGame,
		arg.Console,
		arg.Title,
		arg.Folder,
		arg.IgdbID,
		arg.ReleaseYear,
		arg.CoverImageID,
		arg.Summary,
		arg.Genres,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateGameItem = `-- name: UpdateGameItem :exec
UPDATE game_items SET game_id = ?, kind = ?, label = ?, file = ? WHERE id = ?
`

type UpdateGameItemParams struct {
	GameID int64
	Kind   string
	Label  string
	File   string
	ID     int64
}

func (q *Queries) UpdateGameItem(ctx context.Context, arg UpdateGameItemParams) error {
	_, err := q.db.ExecContext(ctx, updateGameItem,
		arg.GameID,
		arg.Kind,
		arg.Label,
		arg.File,
		arg.ID,
	)
	return err
}
