// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Console struct {
	ID             int64
	Slug           string
	DisplayName    string
	IgdbPlatformID sql.NullInt64
	ReleaseYear    sql.NullInt64
	LogoImageID    sql.NullString
	Extensions     string
	DetectorKey    sql.NullString
	SortOrder      int64
	CreatedAt      string
}
