// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type ConsoleExtension struct {
	Slug      string
	Extension string
}

type ConsoleSetting struct {
	Slug        string
	DisplayName sql.NullString
	SortOrder   int64
	LogoImageID sql.NullString
	ReleaseYear sql.NullInt64
}

type Game struct {
	ID           int64
	Console      string
	Title        string
	Folder       string
	IgdbID       sql.NullInt64
	ReleaseYear  sql.NullInt64
	CoverImageID sql.NullString
	Summary      sql.NullString
	Genres       string
	CreatedAt    string
	UpdatedAt    string
}

type GameItem struct {
	ID           int64
	GameID       int64
	Kind         string
	Label        string
	File         string
	Size         int64
	SourceJob    string
	CreatedAt    string
	TrashEntryID sql.NullInt64
}

type LibraryOperation struct {
	ID          string
	Source      string
	Moves       string
	CreatedDirs string
	CreatedAt   string
}

type ScanPending struct {
	Path    string
	Size    int64
	ModTime string
}

type StagedFile struct {
	JobID        string
	Path         string
	Size         int64
	UnassignedID sql.NullInt64
}

type TrashEntry struct {
	ID        int64
	GameID    sql.NullInt64
	WholeGame int64
	Reason    string
	Dir       string
	TrashedAt string
}

type UnassignedFile struct {
	ID           int64
	Path         string
	Origin       string
	Reason       string
	Size         int64
	ArrivedAt    string
	TrashEntryID sql.NullInt64
	Console      string
	IgdbID       sql.NullInt64
	JobID        string
}

type UploadJob struct {
	ID               string
	FileName         string
	Size             int64
	Received         int64
	Status           string
	Error            string
	Warning          string
	Progress         int64
	Console          string
	Title            string
	IgdbID           sql.NullInt64
	InvalidReason    string
	GroupID          string
	GroupSize        int64
	MergedInto       string
	StoragePath      string
	UnassignedOrigin string
	CreatedAt        string
	UpdatedAt        string
	UnassignedFrom   string
	UnassignedReason string
}
