//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Ok       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ImageSize.
const (
	CoverBig      ImageSize = "cover_big"
	CoverSmall    ImageSize = "cover_small"
	LogoMed       ImageSize = "logo_med"
	ScreenshotMed ImageSize = "screenshot_med"
)

// Valid indicates whether the value is a known member of the ImageSize enum.
func (e ImageSize) Valid() bool {
	switch e {
	case CoverBig:
		return true
	case CoverSmall:
		return true
	case LogoMed:
		return true
	case ScreenshotMed:
		return true
	default:
		return false
	}
}

// Defines values for ItemKind.
const (
	ItemKindBase   ItemKind = "base"
	ItemKindDisc   ItemKind = "disc"
	ItemKindDlc    ItemKind = "dlc"
	ItemKindUpdate ItemKind = "update"
)

// Valid indicates whether the value is a known member of the ItemKind enum.
func (e ItemKind) Valid() bool {
	switch e {
	case ItemKindBase:
		return true
	case ItemKindDisc:
		return true
	case ItemKindDlc:
		return true
	case ItemKindUpdate:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	Cancelled     JobStatus = "cancelled"
	Committing    JobStatus = "committing"
	Done          JobStatus = "done"
	Extracting    JobStatus = "extracting"
	Failed        JobStatus = "failed"
	NeedsPassword JobStatus = "needs_password"
	Review        JobStatus = "review"
	Uploaded      JobStatus = "uploaded"
	Uploading     JobStatus = "uploading"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Committing:
		return true
	case Done:
		return true
	case Extracting:
		return true
	case Failed:
		return true
	case NeedsPassword:
		return true
	case Review:
		return true
	case Uploaded:
		return true
	case Uploading:
		return true
	default:
		return false
	}
}

// Defines values for StagedItemConfidence.
const (
	Extension StagedItemConfidence = "extension"
	Header    StagedItemConfidence = "header"
	None      StagedItemConfidence = "none"
)

// Valid indicates whether the value is a known member of the StagedItemConfidence enum.
func (e StagedItemConfidence) Valid() bool {
	switch e {
	case Extension:
		return true
	case Header:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for StagedItemShape.
const (
	StagedItemShapeDisc   StagedItemShape = "disc"
	StagedItemShapeFile   StagedItemShape = "file"
	StagedItemShapeFolder StagedItemShape = "folder"
)

// Valid indicates whether the value is a known member of the StagedItemShape enum.
func (e StagedItemShape) Valid() bool {
	switch e {
	case StagedItemShapeDisc:
		return true
	case StagedItemShapeFile:
		return true
	case StagedItemShapeFolder:
		return true
	default:
		return false
	}
}

// Console defines model for Console.
type Console struct {
	// DisplayName Example: PlayStation 2
	DisplayName    string   `json:"displayName"`
	Extensions     []string `json:"extensions"`
	Id             int64    `json:"id"`
	IgdbPlatformId *int64   `json:"igdbPlatformId,omitempty"`

	// LogoImageId IGDB image id; render with /api/images/logo_med/{logoImageId}.
	LogoImageId *string `json:"logoImageId,omitempty"`

	// ReleaseYear Example: 2000
	ReleaseYear *int `json:"releaseYear,omitempty"`

	// Slug Folder name in the library (ES-DE style).
	//
	// Example: ps2
	Slug      string `json:"slug"`
	SortOrder int    `json:"sortOrder"`
}

// Health defines model for Health.
type Health struct {
	Checks []HealthCheck `json:"checks"`
	Status HealthStatus  `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// HealthCheck defines model for HealthCheck.
type HealthCheck struct {
	// Message Human readable explanation when the check fails.
	Message *string `json:"message,omitempty"`

	// Name Example: library-writable
	Name string `json:"name"`
	Ok   bool   `json:"ok"`
}

// ImageSize IGDB image size preset.
type ImageSize string

// ItemKind What a stored item is within a game folder.
type ItemKind string

// JobStatus uploading → uploaded → (extracting ⇄ needs_password) → review →
// committing → done; failed and cancelled are terminal.
type JobStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
}

// MetadataGame defines model for MetadataGame.
type MetadataGame struct {
	// CoverImageId Render with /api/images/cover_big/{coverImageId}.
	CoverImageId *string  `json:"coverImageId,omitempty"`
	Genres       []string `json:"genres"`

	// Id IGDB game id.
	Id int64 `json:"id"`

	// Name Example: Mario Kart 8 Deluxe
	Name        string  `json:"name"`
	PlatformIds []int64 `json:"platformIds"`
	ReleaseYear *int    `json:"releaseYear,omitempty"`
	Summary     *string `json:"summary,omitempty"`
}

// MetadataPlatform defines model for MetadataPlatform.
type MetadataPlatform struct {
	Abbreviation *string `json:"abbreviation,omitempty"`

	// Id IGDB platform id.
	Id          int64   `json:"id"`
	LogoImageId *string `json:"logoImageId,omitempty"`

	// Name Example: Wii U
	Name        string `json:"name"`
	ReleaseYear *int   `json:"releaseYear,omitempty"`
}

// PasswordRequest defines model for PasswordRequest.
type PasswordRequest struct {
	Password string `json:"password"`
}

// Problem RFC 9457 problem details.
type Problem struct {
	Detail *string `json:"detail,omitempty"`
	Status int     `json:"status"`
	Title  string  `json:"title"`
	Type   *string `json:"type,omitempty"`
}

// Session defines model for Session.
type Session struct {
	ExpiresAt time.Time `json:"expiresAt"`
}

// StagedItem defines model for StagedItem.
type StagedItem struct {
	Confidence StagedItemConfidence `json:"confidence"`

	// Consoles Candidate console slugs; one when the content was conclusive, empty when unknown.
	Consoles   []string `json:"consoles"`
	DiscNumber *int     `json:"discNumber,omitempty"`

	// DisplayVersion Human version (1.0.3), suggested as the update label.
	DisplayVersion *string `json:"displayVersion,omitempty"`

	// Ignored Junk (readme, .nfo, images) set aside; not stored in the library.
	Ignored bool     `json:"ignored"`
	Parts   []string `json:"parts"`

	// Path Relative to the upload; for discs, the .cue sheet. Identifies the item in the review.
	//
	// Example: Wrapper/INSIDE [0100D2D009028000][v0].nsp
	Path string `json:"path"`

	// Shape file; disc = .cue plus its .bin tracks; folder = folder-format game (PS3), kept whole.
	Shape         StagedItemShape `json:"shape"`
	Size          int64           `json:"size"`
	SuggestedKind *ItemKind       `json:"suggestedKind,omitempty"`

	// TitleId Nintendo Switch title id found in the file name.
	TitleId *string `json:"titleId,omitempty"`

	// VersionCode Numeric version tag ([v196608]).
	VersionCode *string `json:"versionCode,omitempty"`
}

// StagedItemConfidence defines model for StagedItem.Confidence.
type StagedItemConfidence string

// StagedItemShape file; disc = .cue plus its .bin tracks; folder = folder-format game (PS3), kept whole.
type StagedItemShape string

// UploadJob defines model for UploadJob.
type UploadJob struct {
	CreatedAt time.Time `json:"createdAt"`

	// Error Human readable reason (failed, or why a password is needed).
	Error *string `json:"error,omitempty"`

	// FileName Example: INSIDE-Switch-NSP-Base-Game.rar
	FileName string `json:"fileName"`

	// Id Equals the tus upload id.
	Id string `json:"id"`

	// OriginConsole Slug of the console screen the upload started from.
	OriginConsole *string `json:"originConsole,omitempty"`

	// Progress Extraction percentage while status is extracting.
	Progress *int  `json:"progress,omitempty"`
	Received int64 `json:"received"`
	Size     int64 `json:"size"`

	// Status uploading → uploaded → (extracting ⇄ needs_password) → review →
	// committing → done; failed and cancelled are terminal.
	Status    JobStatus `json:"status"`
	UpdatedAt time.Time `json:"updatedAt"`

	// Warning Non-fatal note, e.g. archive file attributes not applied.
	Warning *string `json:"warning,omitempty"`
}

// JobId defines model for JobId.
type JobId = string

// BadGateway RFC 9457 problem details.
type BadGateway = Problem

// BadRequest RFC 9457 problem details.
type BadRequest = Problem

// Conflict RFC 9457 problem details.
type Conflict = Problem

// NotFound RFC 9457 problem details.
type NotFound = Problem

// ServiceUnavailable RFC 9457 problem details.
type ServiceUnavailable = Problem

// TooManyRequests RFC 9457 problem details.
type TooManyRequests = Problem

// Unauthorized RFC 9457 problem details.
type Unauthorized = Problem

// SearchGamesParams defines parameters for SearchGames.
type SearchGamesParams struct {
	Q string `form:"q" json:"q"`

	// PlatformId IGDB platform id (Console.igdbPlatformId).
	PlatformId *int64 `form:"platformId,omitempty" json:"platformId,omitempty"`
	Limit      *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// SearchPlatformsParams defines parameters for SearchPlatforms.
type SearchPlatformsParams struct {
	Q string `form:"q" json:"q"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SubmitJobPasswordJSONRequestBody defines body for SubmitJobPassword for application/json ContentType.
type SubmitJobPasswordJSONRequestBody = PasswordRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Start a session with the shared password
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout End the session on this device
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// GetSession Current session
	// (GET /auth/session)
	GetSession(w http.ResponseWriter, r *http.Request)
	// ListConsoles Consoles in carousel order
	// (GET /consoles)
	ListConsoles(w http.ResponseWriter, r *http.Request)
	// GetHealth Liveness probe and startup diagnostics
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetImage IGDB image (cover or logo) served from the local cache
	// (GET /images/{size}/{imageId})
	GetImage(w http.ResponseWriter, r *http.Request, size ImageSize, imageId string)
	// ListJobs Recent upload jobs, newest first
	// (GET /jobs)
	ListJobs(w http.ResponseWriter, r *http.Request)
	// StreamJobEvents Live job changes (server-sent events)
	// (GET /jobs/events)
	StreamJobEvents(w http.ResponseWriter, r *http.Request)
	// GetJob One upload job
	// (GET /jobs/{id})
	GetJob(w http.ResponseWriter, r *http.Request, id JobId)
	// CancelJob Cancel a job and delete its uploaded data
	// (POST /jobs/{id}/cancel)
	CancelJob(w http.ResponseWriter, r *http.Request, id JobId)
	// ListJobItems Items found in an upload, with console and kind suggestions
	// (GET /jobs/{id}/items)
	ListJobItems(w http.ResponseWriter, r *http.Request, id JobId)
	// SubmitJobPassword Retry extraction of an encrypted archive with its password
	// (POST /jobs/{id}/password)
	SubmitJobPassword(w http.ResponseWriter, r *http.Request, id JobId)
	// SearchGames Search games on IGDB, optionally limited to one platform
	// (GET /metadata/games)
	SearchGames(w http.ResponseWriter, r *http.Request, params SearchGamesParams)
	// SearchPlatforms Search platforms on IGDB (used to add consoles)
	// (GET /metadata/platforms)
	SearchPlatforms(w http.ResponseWriter, r *http.Request, params SearchPlatformsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListConsoles operation middleware
func (siw *ServerInterfaceWrapper) ListConsoles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListConsoles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetImage operation middleware
func (siw *ServerInterfaceWrapper) GetImage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "size" -------------
	var size ImageSize

	err = runtime.BindStyledParameterWithOptions("simple", "size", r.PathValue("size"), &size, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "size", Err: err})
		return
	}

	// ------------- Path parameter "imageId" -------------
	var imageId string

	err = runtime.BindStyledParameterWithOptions("simple", "imageId", r.PathValue("imageId"), &imageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "imageId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetImage(w, r, size, imageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListJobs operation middleware
func (siw *ServerInterfaceWrapper) ListJobs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListJobs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamJobEvents operation middleware
func (siw *ServerInterfaceWrapper) StreamJobEvents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamJobEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJob operation middleware
func (siw *ServerInterfaceWrapper) GetJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelJob operation middleware
func (siw *ServerInterfaceWrapper) CancelJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListJobItems operation middleware
func (siw *ServerInterfaceWrapper) ListJobItems(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListJobItems(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitJobPassword operation middleware
func (siw *ServerInterfaceWrapper) SubmitJobPassword(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id JobId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitJobPassword(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchGames operation middleware
func (siw *ServerInterfaceWrapper) SearchGames(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchGamesParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "platformId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "platformId", r.URL.Query(), &params.PlatformId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "platformId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "platformId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchGames(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchPlatforms operation middleware
func (siw *ServerInterfaceWrapper) SearchPlatforms(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchPlatformsParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchPlatforms(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/session", wrapper.GetSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/consoles", wrapper.ListConsoles)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/metadata/games", wrapper.SearchGames)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/metadata/platforms", wrapper.SearchPlatforms)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/jobs", wrapper.ListJobs)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/jobs/events", wrapper.StreamJobEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/jobs/{id}", wrapper.GetJob)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/jobs/{id}/items", wrapper.ListJobItems)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/jobs/{id}/password", wrapper.SubmitJobPassword)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/jobs/{id}/cancel", wrapper.CancelJob)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/images/{size}/{imageId}", wrapper.GetImage)

	return m
}

type BadGatewayApplicationProblemPlusJSONResponse Problem

type BadRequestApplicationProblemPlusJSONResponse Problem

type ConflictApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type ServiceUnavailableApplicationProblemPlusJSONResponse Problem

type TooManyRequestsApplicationProblemPlusJSONResponse Problem

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login204ResponseHeaders struct {
	SetCookie *string
}

type Login204Response struct {
	Headers Login204ResponseHeaders
}

func (response Login204Response) VisitLoginResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type Login401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response Login401ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response Login429ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	SetCookie *string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type GetSessionRequestObject struct {
}

type GetSessionResponseObject interface {
	VisitGetSessionResponse(w http.ResponseWriter) error
}

type GetSession200JSONResponse Session

func (response GetSession200JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSession401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetSession401ApplicationProblemPlusJSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListConsolesRequestObject struct {
}

type ListConsolesResponseObject interface {
	VisitListConsolesResponse(w http.ResponseWriter) error
}

type ListConsoles200JSONResponse []Console

func (response ListConsoles200JSONResponse) VisitListConsolesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListConsoles401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListConsoles401ApplicationProblemPlusJSONResponse) VisitListConsolesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetImageRequestObject struct {
	Size    ImageSize `json:"size"`
	ImageId string    `json:"imageId"`
}

type GetImageResponseObject interface {
	VisitGetImageResponse(w http.ResponseWriter) error
}

type GetImage200ResponseHeaders struct {
	CacheControl *string
}

type GetImage200ImagejpegResponse struct {
	Body          io.Reader
	Headers       GetImage200ResponseHeaders
	ContentLength int64
}

func (response GetImage200ImagejpegResponse) VisitGetImageResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/jpeg")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetImage200ImagepngResponse struct {
	Body          io.Reader
	Headers       GetImage200ResponseHeaders
	ContentLength int64
}

func (response GetImage200ImagepngResponse) VisitGetImageResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "image/png")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetImage400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetImage400ApplicationProblemPlusJSONResponse) VisitGetImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetImage401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetImage401ApplicationProblemPlusJSONResponse) VisitGetImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetImage404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetImage404ApplicationProblemPlusJSONResponse) VisitGetImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetImage502ApplicationProblemPlusJSONResponse struct {
	BadGatewayApplicationProblemPlusJSONResponse
}

func (response GetImage502ApplicationProblemPlusJSONResponse) VisitGetImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type ListJobsRequestObject struct {
}

type ListJobsResponseObject interface {
	VisitListJobsResponse(w http.ResponseWriter) error
}

type ListJobs200JSONResponse []UploadJob

func (response ListJobs200JSONResponse) VisitListJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListJobs401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListJobs401ApplicationProblemPlusJSONResponse) VisitListJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StreamJobEventsRequestObject struct {
}

type StreamJobEventsResponseObject interface {
	VisitStreamJobEventsResponse(w http.ResponseWriter) error
}

type StreamJobEvents200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response StreamJobEvents200TexteventStreamResponse) VisitStreamJobEventsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type StreamJobEvents401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response StreamJobEvents401ApplicationProblemPlusJSONResponse) VisitStreamJobEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetJobRequestObject struct {
	Id JobId `json:"id"`
}

type GetJobResponseObject interface {
	VisitGetJobResponse(w http.ResponseWriter) error
}

type GetJob200JSONResponse UploadJob

func (response GetJob200JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetJob401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetJob401ApplicationProblemPlusJSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetJob404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetJob404ApplicationProblemPlusJSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelJobRequestObject struct {
	Id JobId `json:"id"`
}

type CancelJobResponseObject interface {
	VisitCancelJobResponse(w http.ResponseWriter) error
}

type CancelJob200JSONResponse UploadJob

func (response CancelJob200JSONResponse) VisitCancelJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CancelJob401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response CancelJob401ApplicationProblemPlusJSONResponse) VisitCancelJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CancelJob404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response CancelJob404ApplicationProblemPlusJSONResponse) VisitCancelJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelJob409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response CancelJob409ApplicationProblemPlusJSONResponse) VisitCancelJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListJobItemsRequestObject struct {
	Id JobId `json:"id"`
}

type ListJobItemsResponseObject interface {
	VisitListJobItemsResponse(w http.ResponseWriter) error
}

type ListJobItems200JSONResponse []StagedItem

func (response ListJobItems200JSONResponse) VisitListJobItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListJobItems401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response ListJobItems401ApplicationProblemPlusJSONResponse) VisitListJobItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListJobItems404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ListJobItems404ApplicationProblemPlusJSONResponse) VisitListJobItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitJobPasswordRequestObject struct {
	Id   JobId `json:"id"`
	Body *SubmitJobPasswordJSONRequestBody
}

type SubmitJobPasswordResponseObject interface {
	VisitSubmitJobPasswordResponse(w http.ResponseWriter) error
}

type SubmitJobPassword202JSONResponse UploadJob

func (response SubmitJobPassword202JSONResponse) VisitSubmitJobPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitJobPassword400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response SubmitJobPassword400ApplicationProblemPlusJSONResponse) VisitSubmitJobPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitJobPassword401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response SubmitJobPassword401ApplicationProblemPlusJSONResponse) VisitSubmitJobPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitJobPassword404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response SubmitJobPassword404ApplicationProblemPlusJSONResponse) VisitSubmitJobPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SubmitJobPassword409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response SubmitJobPassword409ApplicationProblemPlusJSONResponse) VisitSubmitJobPasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type SearchGamesRequestObject struct {
	Params SearchGamesParams
}

type SearchGamesResponseObject interface {
	VisitSearchGamesResponse(w http.ResponseWriter) error
}

type SearchGames200JSONResponse []MetadataGame

func (response SearchGames200JSONResponse) VisitSearchGamesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchGames400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response SearchGames400ApplicationProblemPlusJSONResponse) VisitSearchGamesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SearchGames401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response SearchGames401ApplicationProblemPlusJSONResponse) VisitSearchGamesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SearchGames502ApplicationProblemPlusJSONResponse struct {
	BadGatewayApplicationProblemPlusJSONResponse
}

func (response SearchGames502ApplicationProblemPlusJSONResponse) VisitSearchGamesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type SearchGames503ApplicationProblemPlusJSONResponse struct {
	ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response SearchGames503ApplicationProblemPlusJSONResponse) VisitSearchGamesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SearchPlatformsRequestObject struct {
	Params SearchPlatformsParams
}

type SearchPlatformsResponseObject interface {
	VisitSearchPlatformsResponse(w http.ResponseWriter) error
}

type SearchPlatforms200JSONResponse []MetadataPlatform

func (response SearchPlatforms200JSONResponse) VisitSearchPlatformsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchPlatforms400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response SearchPlatforms400ApplicationProblemPlusJSONResponse) VisitSearchPlatformsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SearchPlatforms401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response SearchPlatforms401ApplicationProblemPlusJSONResponse) VisitSearchPlatformsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SearchPlatforms502ApplicationProblemPlusJSONResponse struct {
	BadGatewayApplicationProblemPlusJSONResponse
}

func (response SearchPlatforms502ApplicationProblemPlusJSONResponse) VisitSearchPlatformsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type SearchPlatforms503ApplicationProblemPlusJSONResponse struct {
	ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response SearchPlatforms503ApplicationProblemPlusJSONResponse) VisitSearchPlatformsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login Start a session with the shared password
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout End the session on this device
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// GetSession Current session
	// (GET /auth/session)
	GetSession(ctx context.Context, request GetSessionRequestObject) (GetSessionResponseObject, error)
	// ListConsoles Consoles in carousel order
	// (GET /consoles)
	ListConsoles(ctx context.Context, request ListConsolesRequestObject) (ListConsolesResponseObject, error)
	// GetHealth Liveness probe and startup diagnostics
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// GetImage IGDB image (cover or logo) served from the local cache
	// (GET /images/{size}/{imageId})
	GetImage(ctx context.Context, request GetImageRequestObject) (GetImageResponseObject, error)
	// ListJobs Recent upload jobs, newest first
	// (GET /jobs)
	ListJobs(ctx context.Context, request ListJobsRequestObject) (ListJobsResponseObject, error)
	// StreamJobEvents Live job changes (server-sent events)
	// (GET /jobs/events)
	StreamJobEvents(ctx context.Context, request StreamJobEventsRequestObject) (StreamJobEventsResponseObject, error)
	// GetJob One upload job
	// (GET /jobs/{id})
	GetJob(ctx context.Context, request GetJobRequestObject) (GetJobResponseObject, error)
	// CancelJob Cancel a job and delete its uploaded data
	// (POST /jobs/{id}/cancel)
	CancelJob(ctx context.Context, request CancelJobRequestObject) (CancelJobResponseObject, error)
	// ListJobItems Items found in an upload, with console and kind suggestions
	// (GET /jobs/{id}/items)
	ListJobItems(ctx context.Context, request ListJobItemsRequestObject) (ListJobItemsResponseObject, error)
	// SubmitJobPassword Retry extraction of an encrypted archive with its password
	// (POST /jobs/{id}/password)
	SubmitJobPassword(ctx context.Context, request SubmitJobPasswordRequestObject) (SubmitJobPasswordResponseObject, error)
	// SearchGames Search games on IGDB, optionally limited to one platform
	// (GET /metadata/games)
	SearchGames(ctx context.Context, request SearchGamesRequestObject) (SearchGamesResponseObject, error)
	// SearchPlatforms Search platforms on IGDB (used to add consoles)
	// (GET /metadata/platforms)
	SearchPlatforms(ctx context.Context, request SearchPlatformsRequestObject) (SearchPlatformsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSession operation middleware
func (sh *strictHandler) GetSession(w http.ResponseWriter, r *http.Request) {
	var request GetSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSession(ctx, request.(GetSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSessionResponseObject); ok {
		if err := validResponse.VisitGetSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListConsoles operation middleware
func (sh *strictHandler) ListConsoles(w http.ResponseWriter, r *http.Request) {
	var request ListConsolesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListConsoles(ctx, request.(ListConsolesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListConsoles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListConsolesResponseObject); ok {
		if err := validResponse.VisitListConsolesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetImage operation middleware
func (sh *strictHandler) GetImage(w http.ResponseWriter, r *http.Request, size ImageSize, imageId string) {
	var request GetImageRequestObject

	request.Size = size
	request.ImageId = imageId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetImage(ctx, request.(GetImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetImage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetImageResponseObject); ok {
		if err := validResponse.VisitGetImageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListJobs operation middleware
func (sh *strictHandler) ListJobs(w http.ResponseWriter, r *http.Request) {
	var request ListJobsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListJobs(ctx, request.(ListJobsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListJobs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListJobsResponseObject); ok {
		if err := validResponse.VisitListJobsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StreamJobEvents operation middleware
func (sh *strictHandler) StreamJobEvents(w http.ResponseWriter, r *http.Request) {
	var request StreamJobEventsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StreamJobEvents(ctx, request.(StreamJobEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StreamJobEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StreamJobEventsResponseObject); ok {
		if err := validResponse.VisitStreamJobEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJob operation middleware
func (sh *strictHandler) GetJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request GetJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJob(ctx, request.(GetJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobResponseObject); ok {
		if err := validResponse.VisitGetJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelJob operation middleware
func (sh *strictHandler) CancelJob(w http.ResponseWriter, r *http.Request, id JobId) {
	var request CancelJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelJob(ctx, request.(CancelJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelJobResponseObject); ok {
		if err := validResponse.VisitCancelJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListJobItems operation middleware
func (sh *strictHandler) ListJobItems(w http.ResponseWriter, r *http.Request, id JobId) {
	var request ListJobItemsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListJobItems(ctx, request.(ListJobItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListJobItems")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListJobItemsResponseObject); ok {
		if err := validResponse.VisitListJobItemsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubmitJobPassword operation middleware
func (sh *strictHandler) SubmitJobPassword(w http.ResponseWriter, r *http.Request, id JobId) {
	var request SubmitJobPasswordRequestObject

	request.Id = id

	var body SubmitJobPasswordJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitJobPassword(ctx, request.(SubmitJobPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitJobPassword")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitJobPasswordResponseObject); ok {
		if err := validResponse.VisitSubmitJobPasswordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchGames operation middleware
func (sh *strictHandler) SearchGames(w http.ResponseWriter, r *http.Request, params SearchGamesParams) {
	var request SearchGamesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchGames(ctx, request.(SearchGamesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchGames")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchGamesResponseObject); ok {
		if err := validResponse.VisitSearchGamesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchPlatforms operation middleware
func (sh *strictHandler) SearchPlatforms(w http.ResponseWriter, r *http.Request, params SearchPlatformsParams) {
	var request SearchPlatformsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchPlatforms(ctx, request.(SearchPlatformsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchPlatforms")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchPlatformsResponseObject); ok {
		if err := validResponse.VisitSearchPlatformsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
